name: flutter_advanced_networkimage
description: An advanced image provider provides caching and retrying for flutter app. Now with zoomable widget and transition to image widget.
version: 0.8.0
homepage: https://github.com/mchome/flutter_advanced_networkimage

environment:
  sdk: '>=2.10.0 <3.0.0'
  flutter: ">=1.10.0 <2.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.12.1
  path_provider: ^2.0.0
  path: 1.8.0
  flutter_svg: 0.19.3

dev_dependencies:
  flutter_test:
    sdk: flutter

#dependency_overrides:
#  path: 1.8.0
